### ISSUE TITLE
[Bugs] package.json 中缺少 electron-builder

### ISSUE THREAD

**Issue by zxp19821005** [JimHans/live2d-kanban-desktop#14]
如题。我已经将其移植到了ArchLinux的AUR[live2d-kanban-desktop](https://aur.archlinux.org/packages/live2d-kanban-desktop)，但是在有用户在编译时各种报错，最近的错误是 https://aur.archlinux.org/packages/live2d-kanban-desktop#comment-976544 ，我检查了下，是package.json中缺少`electron-builder`的定义，在`scripts`段需要用到。希望能够添加。另：我使用`npm`编译打包时各种问题，所以我在AUR上使用了`pnpm`，希望可以考虑使用`pnpm`或者`yarn`来打包。

**Comment by SamLukeYes** [comment]
刚才 google 了一下，[最初的报错](https://aur.archlinux.org/packages/live2d-kanban-desktop#comment-976085)大概是 https://github.com/nodejs/node-gyp/issues/2869 导致的，更新 gyp 版本到 10 以上应该可以解决这个问题

UPDATE：参考[这个回答](https://stackoverflow.com/a/77638742)，尝试在[这个版本的 PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=live2d-kanban-desktop&id=0e3a0db0f21d9cce2d53243fc4b4f107e1a5cdd9) 中加入构建依赖 `python-setuptools`，同样会出现找不到 `electron-builder` 的错误，看来这是两个不同的问题。~~用 pnpm 可以绕过前一个问题大概是因为它不认 package-lock.json~~即使换成 pnpm 也不能绕过前一个错误，用目前最新的 PKGBUILD 仍然会有如下报错：

```
  ⨯ cannot execute  cause=exit status 1
                    out=.../node_modules/get-cursor-position install$ node-gyp rebuild
    .../node_modules/get-cursor-position install: gyp info it worked if it ends with ok
    .../node_modules/get-cursor-position install: gyp info using node-gyp@9.4.1
    .../node_modules/get-cursor-position install: gyp info using node@20.14.0 | linux | x64
    .../node_modules/get-cursor-position install: gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
    .../node_modules/get-cursor-position install: gyp http GET https://electronjs.org/headers/v22.3.27/node-v22.3.27-headers.tar.gz
    .../node_modules/get-cursor-position install: gyp http 200 https://artifacts.electronjs.org/headers/v22.3.27/node-v22.3.27-headers.tar.gz?force_headers_dist=1
    .../node_modules/get-cursor-position install: gyp http GET https://electronjs.org/headers/v22.3.27/SHASUMS256.txt
    .../node_modules/get-cursor-position install: gyp http 200 https://artifacts.electronjs.org/headers/v22.3.27/SHASUMS256.txt?force_headers_dist=1
    .../node_modules/get-cursor-position install: gyp info spawn /usr/bin/python3
    .../node_modules/get-cursor-position install: gyp info spawn args [
    .../node_modules/get-cursor-position install: gyp info spawn args   '/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/gyp/gyp_main.py',
    .../node_modules/get-cursor-position install: gyp info spawn args   'binding.gyp',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-f',
    .../node_modules/get-cursor-position install: gyp info spawn args   'make',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-I',
    .../node_modules/get-cursor-position install: gyp info spawn args   '/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/get-cursor-position@2.0.0/node_modules/get-cursor-position/build/config.gypi',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-I',
    .../node_modules/get-cursor-position install: gyp info spawn args   '/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/addon.gypi',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-I',
    .../node_modules/get-cursor-position install: gyp info spawn args   '/build/live2d-kanban-desktop/src/.electron-gyp/.electron-gyp/22.3.27/include/node/common.gypi',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Dlibrary=shared_library',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Dvisibility=default',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Dnode_root_dir=/build/live2d-kanban-desktop/src/.electron-gyp/.electron-gyp/22.3.27',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Dnode_gyp_dir=/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Dnode_lib_file=/build/live2d-kanban-desktop/src/.electron-gyp/.electron-gyp/22.3.27/<(target_arch)/node.lib',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Dmodule_root_dir=/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/get-cursor-position@2.0.0/node_modules/get-cursor-position',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Dnode_engine=v8',
    .../node_modules/get-cursor-position install: gyp info spawn args   '--depth=.',
    .../node_modules/get-cursor-position install: gyp info spawn args   '--no-parallel',
    .../node_modules/get-cursor-position install: gyp info spawn args   '--generator-output',
    .../node_modules/get-cursor-position install: gyp info spawn args   'build',
    .../node_modules/get-cursor-position install: gyp info spawn args   '-Goutput_dir=.'
    .../node_modules/get-cursor-position install: gyp info spawn args ]
    .../node_modules/get-cursor-position install: Traceback (most recent call last):
    .../node_modules/get-cursor-position install:   File "/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    .../node_modules/get-cursor-position install:     import gyp  # noqa: E402
    .../node_modules/get-cursor-position install:     ^^^^^^^^^^
    .../node_modules/get-cursor-position install:   File "/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    .../node_modules/get-cursor-position install:     import gyp.input
    .../node_modules/get-cursor-position install:   File "/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    .../node_modules/get-cursor-position install:     from distutils.version import StrictVersion
    .../node_modules/get-cursor-position install: ModuleNotFoundError: No module named 'distutils'
    .../node_modules/get-cursor-position install: gyp ERR! configure error 
    .../node_modules/get-cursor-position install: gyp ERR! stack Error: `gyp` failed with exit code: 1
    .../node_modules/get-cursor-position install: gyp ERR! stack     at ChildProcess.onCpExit (/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/lib/configure.js:325:16)
    .../node_modules/get-cursor-position install: gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
    .../node_modules/get-cursor-position install: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    .../node_modules/get-cursor-position install: gyp ERR! System Linux 6.6.32
    .../node_modules/get-cursor-position install: gyp ERR! command "/build/live2d-kanban-desktop/src/.nvm/versions/node/v20.14.0/bin/node" "/build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    .../node_modules/get-cursor-position install: gyp ERR! cwd /build/live2d-kanban-desktop/src/live2d-kanban-desktop-2.8.1/node_modules/.pnpm/get-cursor-position@2.0.0/node_modules/get-cursor-position
    .../node_modules/get-cursor-position install: gyp ERR! node -v v20.14.0
    .../node_modules/get-cursor-position install: gyp ERR! node-gyp -v v9.4.1
    .../node_modules/get-cursor-position install: gyp ERR! not ok 
    .../node_modules/get-cursor-position install: Failed
     ELIFECYCLE  Command failed with exit code 1.
    
                    command=/usr/lib/node_modules/pnpm/bin/pnpm.cjs rebuild get-cursor-position@2.0.0
                    workingDir=
 ELIFECYCLE  Command failed with exit code 1.
==> ERROR: A failure occurred in build().
    Aborting...
```

建议在打包的时候还是沿用上游的 nodejs 包管理器。

**Comment by JimHans** [comment]
看上去是编译get-cursor-position出的错。这个库是个指针跟随库，本来是准备拿来做指针跟随的，然而之后发现它是获取console光标而非指针，不符合要求因此就放弃了，但没管package所以package.json每次还是包含它，甚至每次打包也会编译这东西（我的锅
这个库是没有预编译文件的，因此需要每次打包的时候编译，考虑到这玩意现在已经不再需要了，我更新一下package.json，删除它的引用应该就能解决问题

**Comment by JimHans** [comment]
2.9.0版本已删除该依赖，可以检查一下是否还出现此错误
